<a href="https://colab.research.google.com/github/ipritamdash/lstm-next-word-predictor/blob/main/pytorch_lstm_next_word_predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [ ]:
document = """
Pritam met Suhani in 11th class. Pritam did not know then that Suhani would become the most important part of his life.
Pritam did not know then that Suhani would become the most important part of his life. Suhani noticed Pritam in class, and slowly they started talking.
Suhani noticed Pritam in class, and slowly they started talking. Pritam liked Suhani's way of laughing, and Suhani liked the way Pritam listened.
Pritam liked Suhani's way of laughing, and Suhani liked the way Pritam listened. Every day, Pritam and Suhani would find small reasons to talk.
Every day, Pritam and Suhani would find small reasons to talk. At first, it was just school stuff.
At first, it was just school stuff. Then, it became deeper.
Then, it became deeper. Suhani started waiting for Pritam after class.
Suhani started waiting for Pritam after class. Pritam started saving a seat for Suhani.
Pritam started saving a seat for Suhani. Slowly, Pritam and Suhani became inseparable.
Slowly, Pritam and Suhani became inseparable. After school, Pritam and Suhani would sometimes walk together.
After school, Pritam and Suhani would sometimes walk together. Suhani would tell Pritam about her day.
Suhani would tell Pritam about her day. Pritam would laugh and make Suhani smile.
Pritam would laugh and make Suhani smile. There was something calm in the way they sat quietly together.
There was something calm in the way they sat quietly together. No pressure.
No pressure. No fake energy.
No fake energy. Just real connection.
Just real connection. Pritam started caring about Suhani more than anyone.
Pritam started caring about Suhani more than anyone. Suhani started feeling safe when Pritam was around.
Suhani started feeling safe when Pritam was around. They were not just friends anymore.
They were not just friends anymore. One day, Pritam told Suhani that he liked her.
One day, Pritam told Suhani that he liked her. Suhani smiled and said, “I feel the same.”
Suhani smiled and said, “I feel the same.” That was the start of their story.
That was the start of their story. From that day, Pritam and Suhani were no longer just classmates.
From that day, Pritam and Suhani were no longer just classmates. They were something more.
They were something more. Something beautiful.
Something beautiful. Something that kept growing.
Something that kept growing. When college started, everything changed.
When college started, everything changed. Suhani went to Rajasthan for college.
Suhani went to Rajasthan for college. Pritam stayed in a different city.
Pritam stayed in a different city. It was the start of long-distance.
It was the start of long-distance. Pritam and Suhani didn’t see each other every day now.
Pritam and Suhani didn’t see each other every day now. But they didn’t let go.
But they didn’t let go. Every morning, Pritam would text Suhani.
Every morning, Pritam would text Suhani. Every night, Suhani would wait for Pritam’s call.
Every night, Suhani would wait for Pritam’s call. They missed each other deeply.
They missed each other deeply. But they kept going.
But they kept going. Pritam once travelled to Suhani’s college in Rajasthan.
Pritam once travelled to Suhani’s college in Rajasthan. It was not easy.
It was not easy. But for Suhani, it was worth it.
But for Suhani, it was worth it. When Suhani saw Pritam outside her hostel, she ran and hugged him.
When Suhani saw Pritam outside her hostel, she ran and hugged him. They spent two days together.
They spent two days together. They walked around the city.
They walked around the city. Suhani showed Pritam her favorite chai shop.
Suhani showed Pritam her favorite chai shop. Pritam clicked pictures of Suhani laughing.
Pritam clicked pictures of Suhani laughing. They held hands and didn’t care who was watching.
They held hands and didn’t care who was watching. It felt like old times.
It felt like old times. When Suhani visited Delhi, things felt better.
When Suhani visited Delhi, things felt better. Pritam and Suhani would meet near the metro station.
Pritam and Suhani would meet near the metro station. Suhani would come on her scooty.
Suhani would come on her scooty. Pritam would hop on, and they would just ride.
Pritam would hop on, and they would just ride. No destination.
No destination. No goal.
No goal. Just movement.
Just movement. Sometimes, they went to the park.
Sometimes, they went to the park. Sometimes, they went to food stalls.
Sometimes, they went to food stalls. Suhani loved spicy momos.
Suhani loved spicy momos. Pritam always got two extra plates for her.
Pritam always got two extra plates for her. They would sit on benches and laugh.
They would sit on benches and laugh. They would talk for hours about life, exams, movies, and dreams.
They would talk for hours about life, exams, movies, and dreams. One of their favorite things was just riding around.
One of their favorite things was just riding around. Pritam would hold Suhani tight as she drove the scooty.
Pritam would hold Suhani tight as she drove the scooty. The wind would hit their faces.
The wind would hit their faces. Songs would play from Suhani’s phone.
Songs would play from Suhani’s phone. Sometimes they didn’t talk, but they didn’t need to.
Sometimes they didn’t talk, but they didn’t need to. The silence between Pritam and Suhani was never awkward.
The silence between Pritam and Suhani was never awkward. It was peaceful.
It was peaceful. They went shopping sometimes.
They went shopping sometimes. Not fancy shopping.
Not fancy shopping. Street shopping.
Street shopping. Suhani would try on sunglasses and ask, “Do I look cool?”
Suhani would try on sunglasses and ask, “Do I look cool?” Pritam would say, “You always do.”
Pritam would say, “You always do.” They would buy one thing and joke about ten.
They would buy one thing and joke about ten. Suhani once bought Pritam a silly bracelet.
Suhani once bought Pritam a silly bracelet. Pritam still keeps it.
Pritam still keeps it. Pritam and Suhani have had fights.
Pritam and Suhani have had fights. Big ones.
Big ones. Silent ones.
Silent ones. Emotional ones.
Emotional ones. But they always came back.
But they always came back. No matter how bad the fight was, Pritam would call.
No matter how bad the fight was, Pritam would call. Suhani would pick up.
Suhani would pick up. They would talk and cry and say sorry.
They would talk and cry and say sorry. Then laugh again.
Then laugh again. It was not perfect.
It was not perfect. But it was real.
But it was real. Pritam loves how Suhani talks fast when she’s excited.
Pritam loves how Suhani talks fast when she’s excited. Suhani loves how Pritam tries to act calm but is secretly emotional.
Suhani loves how Pritam tries to act calm but is secretly emotional. They know each other too well.
They know each other too well. Sometimes, Suhani says something and Pritam knows exactly what she means without asking.
Sometimes, Suhani says something and Pritam knows exactly what she means without asking. Sometimes, Pritam stays quiet and Suhani knows he needs her.
Sometimes, Pritam stays quiet and Suhani knows he needs her. It’s been over five years now.
It’s been over five years now. Pritam and Suhani are still together.
Pritam and Suhani are still together. They’ve grown.
They’ve grown. They’ve changed.
They’ve changed. But the bond is stronger.
But the bond is stronger. They’ve done birthdays on video calls.
They’ve done birthdays on video calls. They’ve watched movies while on a call.
They’ve watched movies while on a call. They’ve sent each other random gifts.
They’ve sent each other random gifts. Pritam once sent Suhani a hand-written letter.
Pritam once sent Suhani a hand-written letter. Suhani cried reading it.
Suhani cried reading it. Every year, they make new memories.
Every year, they make new memories. Pritam and Suhani still talk daily.
Pritam and Suhani still talk daily. They still share memes.
They still share memes. They still plan imaginary trips.
They still plan imaginary trips. Sometimes, Pritam says, “One day we’ll live together.”
Sometimes, Pritam says, “One day we’ll live together.” Suhani replies, “With a dog and lots of plants.”
Suhani replies, “With a dog and lots of plants.” Pritam laughs.
Pritam laughs. Suhani laughs louder.
Suhani laughs louder. Sometimes, life gets heavy.
Sometimes, life gets heavy. College, deadlines, future, pressure.
College, deadlines, future, pressure. But somehow, Pritam and Suhani find peace in each other.
But somehow, Pritam and Suhani find peace in each other. Pritam once told Suhani, “You are my calm.”
Pritam once told Suhani, “You are my calm.” Suhani said, “You are my safe space.”
Suhani said, “You are my safe space.” There are hundreds of small stories.
There are hundreds of small stories. The time Suhani got angry over a forgotten date.
The time Suhani got angry over a forgotten date. The time Pritam stayed awake all night because Suhani was sick.
The time Pritam stayed awake all night because Suhani was sick. The time they spent one hour on a video call doing absolutely nothing.
The time they spent one hour on a video call doing absolutely nothing. The time Suhani sent a song and said, “This is us.”
The time Suhani sent a song and said, “This is us.” The time Pritam made a playlist called “Suhani’s Vibe.”
The time Pritam made a playlist called “Suhani’s Vibe.” Pritam and Suhani are still writing their story.
Pritam and Suhani are still writing their story. It’s still happening.
It’s still happening. Every chat, every call, every silly emoji, every shared dream—it all becomes part of this never-ending timeline.
Every chat, every call, every silly emoji, every shared dream—it all becomes part of this never-ending timeline. Pritam doesn’t know how the future will look.
Pritam doesn’t know how the future will look. Suhani doesn’t either.
Suhani doesn’t either. But they both know one thing.
But they both know one thing. If it’s with each other, they’ll figure it out.
If it’s with each other, they’ll figure it out. Pritam and Suhani are proof that love is not about grand gestures.
Pritam and Suhani are proof that love is not about grand gestures. It’s about showing up, again and again.
It’s about showing up, again and again. It’s about texting “I’m here” even when it’s hard.
It’s about texting “I’m here” even when it’s hard. It’s about holding on when everything says let go.
It’s about holding on when everything says let go. Pritam loves Suhani.
Pritam loves Suhani. Suhani loves Pritam.
Suhani loves Pritam. And after all this time, that’s still the most certain thing in their world.
"""


In [ ]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
# tokenize
tokens = word_tokenize(document.lower())

In [ ]:
# build vocab
vocab = {'<unk>':0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

In [ ]:
len(vocab)

376

In [ ]:
input_sentences = document.split('\n')

In [ ]:
# extract sentences from data
def text_to_indices(sentence, vocab):

  numerical_sentence = []

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence


In [ ]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))


In [ ]:
len(input_numerical_sentences)

135

In [ ]:
training_sequence = []
for sentence in input_numerical_sentences:

  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [ ]:
len(training_sequence)

2146

In [ ]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

32

In [ ]:
training_sequence[0]

[1, 2]

In [ ]:
padded_training_sequence=[]
for sequence in training_sequence:
  padded_training_sequence.append(([0]*(max(len_list)-len(sequence)) + sequence))

In [ ]:
len(padded_training_sequence[22])

32

In [ ]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype = torch.long)

In [ ]:
padded_training_sequence.shape

torch.Size([2146, 32])

In [ ]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]

In [ ]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0,   0,  ..., 374, 228,   4],
        [  0,   0,   0,  ..., 228,   4,  99],
        [  0,   0,   0,  ...,   4,  99, 375]])

In [ ]:
y

tensor([  2,   3,   4,  ...,  99, 375,   7])

In [ ]:
class CustomDataset(Dataset):

  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [ ]:
dataset = CustomDataset(X,y)

In [ ]:
len(dataset)

2146

In [ ]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [ ]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

Streaming output truncated to the last 5000 lines.
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0, 205],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,  15, 328,   3, 188, 329, 276,
          54, 330, 331],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,  15, 328,   1, 343,  54, 344, 345,  93,
           3, 117, 130],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  71,  73,  74,   7,
          45,  75,  76],
        [  0,   0,   0,   0,   0,  43, 117, 130,  61, 367, 250,  23, 253,  24,
         253,   7,  43, 117, 130,  61, 368,  93,  94, 117, 369, 370,  97, 371,
          83,  43, 117],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 123,
          51,   3,  23,  43,  44, 